### ISSUE TITLE
RTSP Stream Error

### ISSUE THREAD

**Issue by KISHORE-KUMAR-S** [Yash-Garg/Streamer#2]
Shows error toast message when rtsp streams are added.

**Comment by yash-garg** [comment]
@KISHORE-KUMAR-S is it the same after toggling the `Force RTP TCP connection` too?

Can you provide an example of what all did you put in the config?

**Comment by KISHORE-KUMAR-S** [comment]
rtsp://username:password@ipaddress/channel/01

**Comment by yash-garg** [comment]
@KISHORE-KUMAR-S make sure to not put the `/` before channel in path, since it already considers it by default.

https://github.com/Yash-Garg/Streamer/blob/b1133c9eb966568383d2fc1820bf401891e3e3ff/android/src/main/java/dev/yashgarg/streamer/data/models/StreamConfig.kt#L23-L28
